/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app2;

import io.javalin.Javalin;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Javalin app = Javalin.create(config -> {

        }).start(7001);

        app.get("/", ctx -> ctx.result("Bienvenido a la App 2 :-D"));
    }
}
